local ID = require("scripts/zones/Throne_Room_[S]/IDs")
local entity = {}



entity.onTrade = function(player,npc,trade)

    if trade:hasItemQty(536,1) and trade:getItemCount() == 1 then 	
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.ANCIENT_FLAMES_BECKON)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.ANCIENT_FLAMES_BECKON)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_RITES_OF_LIFE)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_RITES_OF_LIFE)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.BELOW_THE_ARKS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.BELOW_THE_ARKS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_MOTHERCRYSTALS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_MOTHERCRYSTALS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.AN_INVITATION_WEST)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.AN_INVITATION_WEST)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_LOST_CITY)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_LOST_CITY)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.DISTANT_BELIEFS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.DISTANT_BELIEFS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.AN_ETERNAL_MELODY)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.AN_ETERNAL_MELODY)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.ANCIENT_VOWS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.ANCIENT_VOWS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.A_TRANSIENT_DREAM)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.A_TRANSIENT_DREAM)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_CALL_OF_THE_WYRMKING)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_CALL_OF_THE_WYRMKING)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.A_VESSEL_WITHOUT_A_CAPTAIN )
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.A_VESSEL_WITHOUT_A_CAPTAIN)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_ROAD_FORKS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_ROAD_FORKS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.DESCENDANTS_OF_A_LINE_LOST)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.DESCENDANTS_OF_A_LINE_LOST)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.COMEDY_OF_ERRORS_ACT_I)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.COMEDY_OF_ERRORS_ACT_I)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.TENDING_AGED_WOUNDS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.TENDING_AGED_WOUNDS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.DARKNESS_NAMED)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.DARKNESS_NAMED)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.SHELTERING_DOUBT)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.SHELTERING_DOUBT)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_SAVAGE)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_SAVAGE)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_SECRETS_OF_WORSHIP)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_SECRETS_OF_WORSHIP)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.SLANDEROUS_UTTERINGS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.SLANDEROUS_UTTERINGS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_ENDURING_TUMULT_OF_WAR)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_ENDURING_TUMULT_OF_WAR)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.DESIRES_OF_EMPTINESS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.DESIRES_OF_EMPTINESS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THREE_PATHS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THREE_PATHS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.PARTNERS_WITHOUT_FAME)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.PARTNERS_WITHOUT_FAME)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.SPIRAL)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.SPIRAL)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.WHERE_MESSENGERS_GATHER)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.WHERE_MESSENGERS_GATHER)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.FLAMES_FOR_THE_DEAD)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.FLAMES_FOR_THE_DEAD)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.FOR_WHOM_THE_VERSE_IS_SUNG)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.FOR_WHOM_THE_VERSE_IS_SUNG)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.A_PLACE_TO_RETURN)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.A_PLACE_TO_RETURN)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.MORE_QUESTIONS_THAN_ANSWERS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.MORE_QUESTIONS_THAN_ANSWERS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.ONE_TO_BE_FEARED)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.ONE_TO_BE_FEARED)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.CHAINS_AND_BONDS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.CHAINS_AND_BONDS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.FLAMES_IN_THE_DARKNESS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.FLAMES_IN_THE_DARKNESS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.FIRE_IN_THE_EYES_OF_MEN)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.FIRE_IN_THE_EYES_OF_MEN)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.CALM_BEFORE_THE_STORM)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.CALM_BEFORE_THE_STORM)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_WARRIOR_S_PATH)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_WARRIOR_S_PATH)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.EMPTINESS_BLEEDS)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.EMPTINESS_BLEEDS)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.GARDEN_OF_ANTIQUITY)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.GARDEN_OF_ANTIQUITY)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.A_FATE_DECIDED)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.A_FATE_DECIDED)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.WHEN_ANGELS_FALL)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.WHEN_ANGELS_FALL)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.DAWN)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.DAWN)
         player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_LAST_VERSE)
         player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.THE_LAST_VERSE)
         player:addkeyitem(xi.ki.RELIQUIARIUM_KEY)
         player:addKeyItem(xi.ki.PSOXJA_PASS)
         player:addKeyItem(xi.ki.LIGHT_OF_HOLLA)
         player:addKeyItem(xi.ki.LIGHT_OF_DEM)
         player:addKeyItem(xi.ki.LIGHT_OF_MEA)
         player:addKeyItem(xi.ki.LIGHT_OF_VAHZL)
         player:addKeyItem(xi.ki.LIGHT_OF_ALTAIEU)
         player:addKeyItem(xi.ki.ENVELOPE_FROM_MONBERAUX)
         player:addKeyItem(xi.ki.DELKFUTT_RECOGNITION_DEVICE)
         player:addKeyItem(xi.ki.VESSEL_OF_LIGHT)
         player:addKeyItem(xi.ki.LETTERS_FROM_ULMIA_AND_PRISHE)
         player:addKeyItem(xi.ki.BRAND_OF_DAWN)
         player:addKeyItem(xi.ki.BRAND_OF_TWILIGHT)
         player:addKeyItem(xi.ki.TEAR_OF_ALTANA)
         player:addItem(14657,1)
         player:addItem(14672,1)
         player:tradeComplete()
         player:PrintToPlayer(string.format("Mission Overseer : Nice.."), 21) 
		 else player:PrintToPlayer(string.format("Mission Overseer : Noppee.."), 21) 
    end
end
return entity